#!/usr/bin/env python3
"""Export the house's agents and skills into the layouts other runtimes read.

Source of truth: agents/**/*.md (Claude Code subagent format) and skills/*/SKILL.md.
Everything this script writes is generated; edit the source and re-run.

    scripts/export-agents.py                 # write every target into the repo
    scripts/export-agents.py --check         # exit 1 if any generated file is stale
    scripts/export-agents.py --targets codex,gemini --out /path/to/repo

Targets (see PORTABILITY.md for what each runtime reads):
  skills   .agents/skills/<name>/SKILL.md   spec-only frontmatter; Codex, Copilot, Cursor, Gemini
  codex    .codex/agents/<name>.toml        name, description, developer_instructions
  gemini   .gemini/agents/<name>.md         name, description, kind, model + body
  copilot  .github/instructions/*.instructions.md (platform rules by applyTo glob)
           .github/agents/<name>.agent.md  (body trimmed to the 30,000-char cap, with a pointer)
  cursor   .cursor/rules/<stack>.mdc        (platform rules by globs)
"""
import argparse
import functools
import json
import pathlib
import re
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
dumps = functools.partial(json.dumps, ensure_ascii=False)
TARGETS = ("skills", "codex", "gemini", "copilot", "cursor")
SKILL_SPEC_FIELDS = ("name", "description", "license", "compatibility", "metadata", "allowed-tools")
COPILOT_BODY_CAP = 30_000
HEADER = "generated by scripts/export-agents.py from {src}; edit the source, then re-run"

# FILL IN: which paths each platform file applies to in your repo. Same layout
# assumptions as AGENTS.md and ASSUMPTIONS.md.
PLATFORM_GLOBS = {
    "kotlin": ["**/*.kt", "**/*.kts"],
    "android": ["composeApp/**", "androidApp/**", "**/androidMain/**", "**/AndroidManifest.xml"],
    "kmp": ["shared/**"],
    "swift": ["**/*.swift", "**/Package.swift"],
    "ios": ["iosApp/**", "**/*.xcodeproj/**", "**/*.xcconfig", "**/*.storyboard", "**/*.xib"],
    "java": ["**/*.java", "**/pom.xml"],
    "spring": ["server/**", "**/application*.yml", "**/application*.properties"],
    "typescript": ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cjs"],
    "react": ["**/*.tsx", "**/*.jsx"],
}


def parse_frontmatter(text):
    """Return (dict, body). Values are bare strings or JSON-style quoted strings."""
    m = re.match(r"\A---\n(.*?)\n---\n(.*)\Z", text, re.S)
    if not m:
        raise ValueError("no frontmatter")
    meta = {}
    for line in m.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        if value.startswith('"'):
            value = json.loads(value)
        meta[key.strip()] = value
    return meta, m.group(2)


def split_tools(value):
    return [t.strip() for t in value.split(",") if t.strip()] if value else []


def load_agents(root):
    for path in sorted((root / "agents").glob("*/*.md")):
        if path.name == "README.md":
            continue
        meta, body = parse_frontmatter(path.read_text())
        yield path.relative_to(root), meta, body.strip("\n")


def load_skills(root):
    for path in sorted((root / "skills").glob("*/SKILL.md")):
        meta, body = parse_frontmatter(path.read_text())
        yield path.parent, meta, body


def frontmatter(fields):
    lines = ["---"]
    for key, value in fields.items():
        if value is None:
            continue
        lines.append(f"{key}: {dumps(value) if isinstance(value, str) else value}")
    lines.append("---")
    return "\n".join(lines) + "\n"


def trim_body(body, cap, src):
    """Keep the role paragraphs and the House practices section; point at the full file."""
    if len(body) <= cap:
        return body
    intro = body.split("\n## ", 1)[0]
    house = re.search(r"\n(## House practices.*?)(?=\n## |\Z)", body, re.S)
    pointer = (
        f"\n\n## Full definition\n\nThis is the short form (the runtime caps agent prompts at {cap:,} characters). "
        f"Read `{src}` before you start; it is the complete definition and overrides this summary.\n"
    )
    out = intro + ("\n\n" + house.group(1) if house else "") + pointer
    if len(out) > cap:
        out = intro[: cap - len(pointer) - 1] + "\n" + pointer
    return out


def render(root):
    """Return {relative path: content} for every generated file."""
    files = {}
    agents = list(load_agents(root))

    # .agents/skills — the cross-runtime skills directory. Spec fields only.
    for skill_dir, meta, body in load_skills(root):
        name = skill_dir.name
        fields = {k: meta[k] for k in SKILL_SPEC_FIELDS if k in meta}
        files[f".agents/skills/{name}/SKILL.md"] = frontmatter(fields) + body
        for extra in sorted(skill_dir.rglob("*")):
            if extra.is_file() and extra.name != "SKILL.md":
                files[f".agents/skills/{name}/{extra.relative_to(skill_dir)}"] = extra.read_text()

    for src, meta, body in agents:
        name = meta["name"]
        # Codex: TOML, literal multi-line string so backslashes in the body survive.
        if "'''" in body:
            raise SystemExit(f"{src}: body contains ''' which a TOML literal string cannot hold")
        files[f".codex/agents/{name}.toml"] = (
            f"# {HEADER.format(src=src)}\n"
            f"name = {dumps(name)}\n"
            f"description = {dumps(meta['description'])}\n"
            f"developer_instructions = '''\n{body}\n'''\n"
        )
        # Gemini CLI: markdown with its own fields; tools omitted so it inherits all.
        files[f".gemini/agents/{name}.md"] = (
            frontmatter({"name": name, "description": meta["description"], "kind": "local", "model": "inherit"})
            + f"<!-- {HEADER.format(src=src)} -->\n\n" + body + "\n"
        )
        # GitHub Copilot: tools omitted (defaults to all); body under the cap.
        files[f".github/agents/{name}.agent.md"] = (
            frontmatter({"name": name, "description": meta["description"]})
            + f"<!-- {HEADER.format(src=src)} -->\n\n" + trim_body(body, COPILOT_BODY_CAP, src) + "\n"
        )

    # Platform rules, auto-attached by path.
    for stack, globs in PLATFORM_GLOBS.items():
        src = pathlib.Path("platform") / f"AGENTS.{stack}.md"
        text = (root / src).read_text()
        title = text.splitlines()[0].lstrip("# ").strip()
        files[f".github/instructions/{stack}.instructions.md"] = (
            frontmatter({"description": title, "applyTo": ",".join(globs)})
            + f"<!-- {HEADER.format(src=src)} -->\n\n" + text
        )
        files[f".cursor/rules/{stack}.mdc"] = (
            "---\n"
            f"description: {dumps(title)}\n"
            f"globs: {dumps(','.join(globs))}\n"
            "alwaysApply: false\n"
            "---\n"
            f"<!-- {HEADER.format(src=src)} -->\n\n" + text
        )
    return files


def wanted(path, targets):
    prefix = {
        "skills": (".agents/skills/",),
        "codex": (".codex/",),
        "gemini": (".gemini/",),
        "copilot": (".github/instructions/", ".github/agents/"),
        "cursor": (".cursor/",),
    }
    return any(path.startswith(p) for t in targets for p in prefix[t])


def validate(files):
    for path, content in files.items():
        if path.endswith(".toml"):
            tomllib.loads(content)
        elif path.startswith(".github/agents/"):
            _, body = parse_frontmatter(content)
            if len(body) > COPILOT_BODY_CAP:
                raise SystemExit(f"{path}: body is {len(body)} chars, over the {COPILOT_BODY_CAP} cap")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--targets", default=",".join(TARGETS), help="comma-separated subset of: " + ",".join(TARGETS))
    ap.add_argument("--out", default=str(ROOT), help="repository to write into (default: this repo)")
    ap.add_argument("--check", action="store_true", help="report stale or missing files instead of writing")
    args = ap.parse_args()
    targets = [t for t in args.targets.split(",") if t]
    unknown = set(targets) - set(TARGETS)
    if unknown:
        ap.error(f"unknown targets: {', '.join(sorted(unknown))}")

    files = {p: c for p, c in render(ROOT).items() if wanted(p, targets)}
    validate(files)
    out = pathlib.Path(args.out)

    if args.check:
        stale = [p for p, c in files.items() if not (out / p).exists() or (out / p).read_text() != c]
        for p in stale:
            print(f"stale: {p}")
        print(f"{len(files) - len(stale)} up to date, {len(stale)} stale")
        sys.exit(1 if stale else 0)

    for p, c in files.items():
        dest = out / p
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(c)
    print(f"wrote {len(files)} files into {out}")


if __name__ == "__main__":
    main()
